steps:
  #Install, compile & copy shared-types

  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    env: ["NODE_ENV=development"]
    id: "installjs"

  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - |
        sed -i 's/%URL%/$BRANCH_NAME/g' app.yaml
    entrypoint: bash
    id: "edityaml"
    wait_for: ["installjs"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - |
        version=$BRANCH_NAME
        gcloud beta app deploy app.yaml --version=${version,,} --no-promote
    entrypoint: bash
    id: "deploy"
    wait_for: ["edityaml"]

  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "--tag=eu.gcr.io/$PROJECT_ID/testcafe:latest"
      - "--file=dockerfile"
      - "."
    id: "testcafedocker"
    wait_for: ["deploy"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/testcafe:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "testcafe:latest",
        "--image",
        "gcr.io/$PROJECT_ID/testcafe:latest",
        "--platform",
        "managed",
        "--quiet",
      ]
    images:
      - gcr.io/$PROJECT_ID/[SERVICE-NAME]

timeout: 1800s
