steps:
  #Install, compile & copy shared-types

  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    env: ["NODE_ENV=development"]
    id: "installjs"

  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - |
        gcloud beta app deploy app.yaml --version=${$BRANCH_NAME,,} --no-promote
    entrypoint: bash
    id: "deploy"
    wait_for: ["installjs"]

timeout: 1800s
